// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ssl_vision_wrapper.proto
// Protobuf C++ Version: 5.29.0-dev

#ifndef GOOGLE_PROTOBUF_INCLUDED_ssl_5fvision_5fwrapper_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ssl_5fvision_5fwrapper_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "ssl_vision_detection.pb.h"
#include "ssl_vision_geometry.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ssl_5fvision_5fwrapper_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ssl_5fvision_5fwrapper_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ssl_5fvision_5fwrapper_2eproto;
class SSL_WrapperPacket;
struct SSL_WrapperPacketDefaultTypeInternal;
extern SSL_WrapperPacketDefaultTypeInternal _SSL_WrapperPacket_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class SSL_WrapperPacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:SSL_WrapperPacket) */ {
 public:
  inline SSL_WrapperPacket() : SSL_WrapperPacket(nullptr) {}
  ~SSL_WrapperPacket() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SSL_WrapperPacket(
      ::google::protobuf::internal::ConstantInitialized);

  inline SSL_WrapperPacket(const SSL_WrapperPacket& from) : SSL_WrapperPacket(nullptr, from) {}
  inline SSL_WrapperPacket(SSL_WrapperPacket&& from) noexcept
      : SSL_WrapperPacket(nullptr, std::move(from)) {}
  inline SSL_WrapperPacket& operator=(const SSL_WrapperPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline SSL_WrapperPacket& operator=(SSL_WrapperPacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SSL_WrapperPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const SSL_WrapperPacket* internal_default_instance() {
    return reinterpret_cast<const SSL_WrapperPacket*>(
        &_SSL_WrapperPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SSL_WrapperPacket& a, SSL_WrapperPacket& b) { a.Swap(&b); }
  inline void Swap(SSL_WrapperPacket* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SSL_WrapperPacket* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SSL_WrapperPacket* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<SSL_WrapperPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SSL_WrapperPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SSL_WrapperPacket& from) { SSL_WrapperPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(SSL_WrapperPacket* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "SSL_WrapperPacket"; }

 protected:
  explicit SSL_WrapperPacket(::google::protobuf::Arena* arena);
  SSL_WrapperPacket(::google::protobuf::Arena* arena, const SSL_WrapperPacket& from);
  SSL_WrapperPacket(::google::protobuf::Arena* arena, SSL_WrapperPacket&& from) noexcept
      : SSL_WrapperPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDetectionFieldNumber = 1,
    kGeometryFieldNumber = 2,
  };
  // optional .SSL_DetectionFrame detection = 1;
  bool has_detection() const;
  void clear_detection() ;
  const ::SSL_DetectionFrame& detection() const;
  PROTOBUF_NODISCARD ::SSL_DetectionFrame* release_detection();
  ::SSL_DetectionFrame* mutable_detection();
  void set_allocated_detection(::SSL_DetectionFrame* value);
  void unsafe_arena_set_allocated_detection(::SSL_DetectionFrame* value);
  ::SSL_DetectionFrame* unsafe_arena_release_detection();

  private:
  const ::SSL_DetectionFrame& _internal_detection() const;
  ::SSL_DetectionFrame* _internal_mutable_detection();

  public:
  // optional .SSL_GeometryData geometry = 2;
  bool has_geometry() const;
  void clear_geometry() ;
  const ::SSL_GeometryData& geometry() const;
  PROTOBUF_NODISCARD ::SSL_GeometryData* release_geometry();
  ::SSL_GeometryData* mutable_geometry();
  void set_allocated_geometry(::SSL_GeometryData* value);
  void unsafe_arena_set_allocated_geometry(::SSL_GeometryData* value);
  ::SSL_GeometryData* unsafe_arena_release_geometry();

  private:
  const ::SSL_GeometryData& _internal_geometry() const;
  ::SSL_GeometryData* _internal_mutable_geometry();

  public:
  // @@protoc_insertion_point(class_scope:SSL_WrapperPacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 2,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_SSL_WrapperPacket_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SSL_WrapperPacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::SSL_DetectionFrame* detection_;
    ::SSL_GeometryData* geometry_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ssl_5fvision_5fwrapper_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SSL_WrapperPacket

// optional .SSL_DetectionFrame detection = 1;
inline bool SSL_WrapperPacket::has_detection() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.detection_ != nullptr);
  return value;
}
inline const ::SSL_DetectionFrame& SSL_WrapperPacket::_internal_detection() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::SSL_DetectionFrame* p = _impl_.detection_;
  return p != nullptr ? *p : reinterpret_cast<const ::SSL_DetectionFrame&>(::_SSL_DetectionFrame_default_instance_);
}
inline const ::SSL_DetectionFrame& SSL_WrapperPacket::detection() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:SSL_WrapperPacket.detection)
  return _internal_detection();
}
inline void SSL_WrapperPacket::unsafe_arena_set_allocated_detection(::SSL_DetectionFrame* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.detection_);
  }
  _impl_.detection_ = reinterpret_cast<::SSL_DetectionFrame*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SSL_WrapperPacket.detection)
}
inline ::SSL_DetectionFrame* SSL_WrapperPacket::release_detection() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::SSL_DetectionFrame* released = _impl_.detection_;
  _impl_.detection_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::SSL_DetectionFrame* SSL_WrapperPacket::unsafe_arena_release_detection() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:SSL_WrapperPacket.detection)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::SSL_DetectionFrame* temp = _impl_.detection_;
  _impl_.detection_ = nullptr;
  return temp;
}
inline ::SSL_DetectionFrame* SSL_WrapperPacket::_internal_mutable_detection() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.detection_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::SSL_DetectionFrame>(GetArena());
    _impl_.detection_ = reinterpret_cast<::SSL_DetectionFrame*>(p);
  }
  return _impl_.detection_;
}
inline ::SSL_DetectionFrame* SSL_WrapperPacket::mutable_detection() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::SSL_DetectionFrame* _msg = _internal_mutable_detection();
  // @@protoc_insertion_point(field_mutable:SSL_WrapperPacket.detection)
  return _msg;
}
inline void SSL_WrapperPacket::set_allocated_detection(::SSL_DetectionFrame* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.detection_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.detection_ = reinterpret_cast<::SSL_DetectionFrame*>(value);
  // @@protoc_insertion_point(field_set_allocated:SSL_WrapperPacket.detection)
}

// optional .SSL_GeometryData geometry = 2;
inline bool SSL_WrapperPacket::has_geometry() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.geometry_ != nullptr);
  return value;
}
inline const ::SSL_GeometryData& SSL_WrapperPacket::_internal_geometry() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::SSL_GeometryData* p = _impl_.geometry_;
  return p != nullptr ? *p : reinterpret_cast<const ::SSL_GeometryData&>(::_SSL_GeometryData_default_instance_);
}
inline const ::SSL_GeometryData& SSL_WrapperPacket::geometry() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:SSL_WrapperPacket.geometry)
  return _internal_geometry();
}
inline void SSL_WrapperPacket::unsafe_arena_set_allocated_geometry(::SSL_GeometryData* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.geometry_);
  }
  _impl_.geometry_ = reinterpret_cast<::SSL_GeometryData*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SSL_WrapperPacket.geometry)
}
inline ::SSL_GeometryData* SSL_WrapperPacket::release_geometry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::SSL_GeometryData* released = _impl_.geometry_;
  _impl_.geometry_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::SSL_GeometryData* SSL_WrapperPacket::unsafe_arena_release_geometry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:SSL_WrapperPacket.geometry)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::SSL_GeometryData* temp = _impl_.geometry_;
  _impl_.geometry_ = nullptr;
  return temp;
}
inline ::SSL_GeometryData* SSL_WrapperPacket::_internal_mutable_geometry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.geometry_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::SSL_GeometryData>(GetArena());
    _impl_.geometry_ = reinterpret_cast<::SSL_GeometryData*>(p);
  }
  return _impl_.geometry_;
}
inline ::SSL_GeometryData* SSL_WrapperPacket::mutable_geometry() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::SSL_GeometryData* _msg = _internal_mutable_geometry();
  // @@protoc_insertion_point(field_mutable:SSL_WrapperPacket.geometry)
  return _msg;
}
inline void SSL_WrapperPacket::set_allocated_geometry(::SSL_GeometryData* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.geometry_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.geometry_ = reinterpret_cast<::SSL_GeometryData*>(value);
  // @@protoc_insertion_point(field_set_allocated:SSL_WrapperPacket.geometry)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ssl_5fvision_5fwrapper_2eproto_2epb_2eh
