[build-system]
requires = ["setuptools>=61.0.0", "swig"]
build-backend = "setuptools.build_meta"

[project]
name = "world_model"
requires-python = ">=3.9"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]