name: build-TC

on: push

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix: 
        config:
          - {
              name: "MSVC", artifact: "WIN-MSVC.tar.xz",
              os: windows-lastest,
              cc: "cl",
              cxx: "cl",
              environment_script: "C:/Program Files(x86)/Miscrosoft Visual Studio/2022/BuildTools/VC/Build/vcvars64.bat"
            }
    steps:
    - uses: actions/checkout@v4
    - name: tc
      id: tc
      run: |
        mkdir build/
        cd build/
        cmake ../ -DCMAKE_PREFIX_PATH="C:/vcpkg/packages/protobuf_x64-windows;C:/vcpkg/packages/abseil_x64-windows"
        cmake --build . --clean-first